### ISSUE TITLE
get values ​​inconsistent

### ISSUE THREAD

**Issue by icyfox168168** [li-script/lightning#6]
printf("%d\n", 0x7fffffffffffffff % 3);
	auto* Ll = vm::create();
	lib::register_std(Ll);
	handle_repl_io(Ll, "a=0x7fffffffffffffff \r\n b=3\r\n c=a%b\r\n");
	return 0;

1

2

**Comment by can1357** [comment]
This is due to the fact that latter is floating point and it can't hold a 62 bit integer.
